/*
 * @Date: 2023-01-02 04:31:36
 * @LastEditTime: 2025-12-01
 */
/* eslint-disable indent */
/* eslint-disable no-tabs */
/* eslint-disable semi */
import _ from 'lodash';

// NEW 標籤顯示期間（月份）- 可自行調整此數值
export const NEW_DISPLAY_MONTHS = 6;

// white-space: pre;

const inventory = [
	{
		id: 1,
		category: '(無糖)無內餡 No Sugar Added',
		name: '白饅頭',
		ename: 'Plain Mantou',
		description: '',
		price: 16,
		type: '素 Vegan',
		pic: './plainMantou.webp',
		do: '天天有',
	},
	{
		id: 2,
		category: '(無糖)無內餡 No Sugar Added',
		name: '伯爵牛奶饅頭',
		ename: 'Earl Milk Mantou',
		description: '唐寧',
		price: 27,
		type: '奶素 Lacto-Vegetarian',
		pic: './earlMilkMantou.webp',
		do: '製作日：2, 6',
	},
	{
		id: 3,
		category: '(無糖)無內餡 No Sugar Added',
		name: '牛奶饅頭',
		ename: 'Milk Mantou',
		description: '紐西蘭奶粉',
		price: 22,
		type: '奶素 Lacto-Vegetarian',
		pic: './milkMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 4,
		category: '(無糖)無內餡 No Sugar Added',
		name: '藜麥饅頭',
		ename: 'Quinoa Mantou',
		description: '30%全麥',
		price: 22,
		type: '素 Vegan',
		pic: './quinoaMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 5,
		category: '(無糖)無內餡 No Sugar Added',
		name: '薑黃起司饅頭',
		ename: 'Turmeric Cheese Mantou',
		description: '提拉姆起司',
		price: 27,
		type: '奶素 Lacto-Vegetarian',
		pic: './turmericCheeseMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 6,
		category: '(無糖)無內餡 No Sugar Added',
		name: '全麥饅頭',
		ename: 'Whole-Wheat Mantou',
		description: '100%全麥',
		price: 20,
		type: '素 Vegan',
		pic: './wholeWheatMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 7,
		category: '(無糖)無內餡 No Sugar Added',
		name: '超麥饅頭',
		ename: 'Nuts Whole-Wheat Mantou',
		description: '100%全麥, 核, 芝, 亞, 藜',
		price: 27,
		type: '素 Vegan',
		pic: './nutsWholeWheatMantou.webp',
		do: '製作日：3',
	},
	{
		id: 8,
		category: '(無糖)無內餡 No Sugar Added',
		name: '穀物南瓜饅頭',
		ename: 'Grain Pumpkin Mantou',
		description: '50%全麥, 小米, 蕎麥, 藜麥',
		price: 27,
		type: '素 Vegan',
		pic: './grainPumpkinMantou.webp',
		do: '製作日：6',
	},
	{
		id: 9,
		category: '(無糖)無內餡 No Sugar Added',
		name: '牛奶芋絲饅頭',
		ename: 'Taro Shreds Milk Mantou',
		description: '',
		price: 27,
		type: '奶素 Lacto-Vegetarian',
		pic: './taroShredsMilkMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 10,
		category: '(無糖)無內餡 No Sugar Added',
		name: '燕麥南瓜饅頭',
		ename: 'Oatmeal & Pumpkin Mantou',
		description: '50%全麥, 燕麥, 南瓜',
		price: 27,
		type: '素 Vegan',
		pic: './wheatPumpkinMantou.webp',
		do: '製作日：1, 6',
	},
	{
		id: 11,
		category: '(無糖)無內餡 No Sugar Added',
		name: '肉桂饅頭',
		ename: 'Cinnamon Mantou',
		description: '30%全麥, 肉桂, 奇亞籽',
		price: 27,
		type: '素 Vegan',
		pic: './cinnamon.webp',
		do: '製作日：1, 3, 6',
		addedDate: '2025-12-25',
	},
	{
		id: 12,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '黑糖饅頭',
		ename: 'Brown Suger Mantou',
		description: '',
		price: 17,
		type: '素 Vegan',
		pic: './brownSugerMantou.webp',
		do: '天天有',
	},
	{
		id: 13,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '芝麻多饅頭',
		ename: 'Sesame Mantou',
		description: '',
		price: 23,
		type: '素 Vegan',
		pic: './sesameMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 14,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '紫米饅頭',
		ename: 'Purple Rice Mantou',
		description: '',
		price: 22,
		type: '素 Vegan',
		pic: './purpleRiceMantou_1.webp',
		do: '須預訂',
	},
	{
		id: 15,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '可可饅頭',
		ename: 'Cacao Mantou',
		description: '',
		price: 25,
		type: '素 Vegan',
		pic: './cacaoMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 16,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '抹茶饅頭',
		ename: 'Matcha Mantou',
		description: '自然農法抹茶',
		price: 25,
		type: '素 Vegan',
		pic: './matchaMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 17,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '土豆饅頭',
		ename: 'Peanut Mantou',
		description: '柴燒烘烤/金弘花生',
		price: 25,
		type: '素 Vegan',
		pic: './peanutMantou.webp',
		do: '須預訂：5',
	},
	{
		id: 18,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '芋絲饅頭',
		ename: 'Taro-Shreds Mantou',
		description: '低糖微甜',
		price: 27,
		type: '素 Vegan',
		pic: './taroShredsMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 19,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '鐵觀音饅頭',
		ename: 'Tieguanyin Mantou',
		description: '低糖微甜',
		price: 27,
		type: '素 Vegan',
		pic: './tieguanyinMantou.webp',
		do: '製作日：1, 3',
	},
	{
		id: 20,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '莓果牛奶饅頭',
		ename: 'Cranberry Milk Mantou',
		description: '低糖微甜',
		price: 27,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryMilkMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 21,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '莓果饅頭',
		ename: 'Berries Mantou',
		description: '(低糖微甜) 黑, 藍, 覆盆, 蔓越莓',
		price: 27,
		type: '素 Vegan',
		pic: './berriesMantou.webp',
		do: '天天有',
	},
	{
		id: 22,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋頭多',
		ename: 'Taro-Filled Mantou',
		description: '',
		price: 35,
		type: '素 Vegan',
		pic: './taroFilledMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 23,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶芋頭多',
		ename: 'Milk Taro-Filled Mantou',
		description: '',
		price: 35,
		type: '奶素 Lacto-Vegetarian',
		pic: './taroFilledMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 24,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋頭紅豆',
		ename: 'Taro & Red Bean-Filled Mantou',
		description: '',
		price: 32,
		type: '奶素 Lacto-Vegetarian',
		pic: './taroRedBeanFilledMantou.webp',
		do: '天天有',
	},
	{
		id: 25,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋泥起司',
		ename: 'Mashed Taro-Filled Cheese Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './01.webp',
		do: '天天有',
	},
	{
		id: 26,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋泥肉鬆',
		ename: 'Mashed Taro & Meat Floss-Filled Mantou',
		description: '',
		price: 36,
		type: '葷 Non Vegetarian',
		pic: './mashedTaroMeatFlossFilledMantou.webp',
		do: '天天有',
	},
	{
		id: 27,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '肉桂芝麻核桃',
		ename: 'Sesame & Walnut-Filled Cinnamon Mantou',
		description: '',
		price: 38,
		type: '素 Vegan',
		pic: './sesameWalnutFilledCinnamon.webp',
		do: '製作日：1, 3, 6',
		addedDate: '2025-12-25',
	},
	{
		id: 28,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '肉桂花生腰果',
		ename: 'Peanuts & Cashews-Filled Cinnamon Mantou',
		description: '',
		price: 38,
		type: '素 Vegan',
		pic: './peanutsCashews-FilledCinnamon.webp',
		do: '製作日：1, 3, 6',
		addedDate: '2025-12-25',
	},
	{
		id: 29,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '肉桂葡萄奶酥',
		ename: 'Grape & Creamy Milk Butter-Filled Cinnamon Mantou',
		description: '',
		price: 38,
		type: '奶素 Lacto-Vegetarian',
		pic: './grapeCreamyMilkButter-FilledCinnamon.webp',
		do: '製作日：1, 3, 6',
		addedDate: '2025-12-25',
	},
	{
		id: 30,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '鐵觀音奶酪核桃',
		ename: 'Walnut & Cream Cheese-Filled Tieguanyin Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './walnutCreamCheeseFilledTieguanyinMantou.webp',
		do: '製作日：1, 3',
	},
	{
		id: 31,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '鐵觀音紅豆',
		ename: 'Red Bean-Filled Tieguanyin Mantou',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './redBeanFilledTieguanyinMantou.webp',
		do: '製作日：1, 3',
	},
	{
		id: 32,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '堅果多',
		ename: 'Nuts-Filled Mantou',
		description: '',
		price: 33,
		type: '素 Vegan',
		pic: './nutsFilledMantou.webp',
		do: '天天有',
	},
	{
		id: 33,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芝麻花生捲',
		ename: 'Peanut-Filled Sesame Mantou Roll',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './peanutFilledSesameMantouRoll.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 34,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '土豆芝麻捲',
		ename: 'Sesame-Filled Peanut Mantou Roll',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './sesameFilledPeanutMantouRoll.webp',
		do: '製作日：5',
	},
	{
		id: 35,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '土豆栗子',
		ename: 'Chesnut-Filled Peanut Mantou',
		description: '',
		price: 35,
		type: '素 Vegan',
		pic: './chesnutFilledPeanutMantou.webp',
		do: '製作日：5',
	},
	{
		id: 36,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可起司',
		ename: 'Cacao Cheese Mantou',
		description: '',
		price: 32,
		type: '奶素 Lacto-Vegetarian',
		pic: './cacaoCheeseMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 37,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可栗子',
		ename: 'Chesnut-Filled Cacao Mantou',
		description: '',
		price: 38,
		type: '素 Vegan',
		pic: './chesnutFilledCacaoMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 38,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可蔓越莓',
		ename: 'Cranberry-Filled Cacao Mantou',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './cranberryFilledCacaoMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 39,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可花生夏威夷果',
		ename: 'Peanut & Macadamia-Filled Cacao Mantou',
		description: '',
		price: 38,
		type: '素 Vegan',
		pic: './peanutMacadamia-FilledCacao.webp',
		do: '製作日：1, 3, 6',
		addedDate: '2025-12-25',
	},
	{
		id: 40,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可奶酪蔓越莓',
		ename: 'Cranberry & Cream Cheese-Filled Cacao Mantou',
		description: '菲力奶油',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamCheeseFilledCacaoMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 41,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可栗子起司',
		ename: 'Chestnut & Cheese-Filled Cacao Mantou',
		description: '',
		price: 38,
		type: '奶素 Lacto-Vegetarian',
		pic: './chestnutCheese-FilledCacao.webp',
		do: '製作日：1, 3, 6',
		addedDate: '2025-12-25',
	},
	{
		id: 42,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶芝麻捲',
		ename: 'Milk & Sesame Mantou Roll',
		description: '',
		price: 32,
		type: '奶素 Lacto-Vegetarian',
		pic: './milkSesameMantouRoll_1.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 43,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶栗子起司',
		ename: 'Chesnut & Cheese-Filled Milk Mantou',
		description: '',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './chesnutCheeseFilledMilkMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 44,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶奶酪蔓越莓',
		ename: 'Cranberry & Cream Cheese-Filled Milk Mantou',
		description: '菲力奶油',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamCheeseFilledMilkMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 45,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶蔓越莓奶酥',
		ename: 'Cranberry & Creamy Milk Butter-Filled Milk Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamyMilkButterFilledMilkMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 46,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '紫米堅果地瓜',
		ename: 'Sweet Potato & Nuts-Filled Purple Rice Mantou',
		description: '',
		price: 35,
		type: '素 Vegan',
		pic: './sweetPotatoNutsFilledPurpleRiceMantou.webp',
		do: '天天有',
	},
	{
		id: 47,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '紫米紅豆',
		ename: 'Red Bean-Filled Purple Rice Mantou',
		description: '小紅豆+花豆',
		price: 28,
		type: '奶素 Lacto-Vegetarian',
		pic: './redBeanFilledPurpleRiceMantou.webp',
		do: '天天有',
	},
	{
		id: 48,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶奶酪栗子',
		ename: 'Chesnut & Cream Cheese-Filled Matcha Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './chesnutCreamCheeseFilledMatchaMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 49,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶紅豆',
		ename: 'Red Bean-Filled Matcha Mantou',
		description: '小紅豆+花豆',
		price: 30,
		type: '素 Vegan',
		pic: './redBeanFilledMatchaMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 50,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶奶酪蔓越莓',
		ename: 'Cranberry & Cream Cheese-Filled Matcha Mantou',
		description: '',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamCheeseFilledMatchaMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 51,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶芋頭',
		ename: 'Taro-Filled Matcha Mantou',
		description: '',
		price: 34,
		type: '素 Vegan',
		pic: './taroFilledMatchaMantou.webp',
		do: '製作日：2, 5',
	},
	{
		id: 52,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶奶酪雙果',
		ename: 'Passion fruit & Macadamia nuts-Filled Matcha Mantou',
		description: '百香果+夏威夷果',
		price: 38,
		type: '奶素 Lacto-Vegetarian',
		pic: './passionfruitMacadamianuts-FilledMatcha.webp',
		do: '製作日：2, 5',
		addedDate: '2025-12-25',
	},
	{
		id: 53,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '藜麥芝麻捲',
		ename: 'Quinoa & Sesame Mantou Roll',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './quinoaSesameMantouRoll.webp',
		do: '製作日：2, 5',
	},
	{
		id: 54,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '藜麥芋頭',
		ename: 'Taro-Filled Quinoa Mantou',
		description: '',
		price: 34,
		type: '素 Vegan',
		pic: './taroFilledQuinoaMantou.webp',
		do: '須預訂：2, 5',
	},
	{
		id: 55,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '藜麥堅果多',
		ename: 'Nuts-Filled Quinoa Mantou',
		description: '無糖需預訂',
		price: 35,
		type: '素 Vegan',
		pic: './nutsFilledQuinoaMantou.webp',
		do: '須預訂：2, 5',
	},
	{
		id: 56,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '蔾麥南瓜夏威夷果',
		ename: 'Pumpkin & Macadamia-Filled Quinoa Mantou',
		description: '',
		price: 38,
		type: '素 Vegan',
		pic: './pumpkinMacadamia-FilledQuinoa.webp',
		do: '製作日：2, 5',
		addedDate: '2025-12-25',
	},
	{
		id: 57,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '起司紅豆',
		ename: 'Red Bean-Filled Cheese Mantou',
		description: '安佳起司',
		price: 28,
		type: '奶素 Lacto-Vegetarian',
		pic: './redBeanFilledCheeseMantou.webp',
		do: '須預訂',
	},
	{
		id: 58,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可奶酥',
		ename: 'Creamy Milk Butter-Filled Cacao Mantou',
		description: '可可/抹茶/花生',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './creamyMilkButterFilledCacaoMantou.webp',
		do: '製作日：1, 3, 6',
	},
	{
		id: 59,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '伯爵奶酥',
		ename: 'Creamy Milk Butter-Filled Earl Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './creamyMilkButterFilledEarlMantou.webp',
		do: '製作日：2, 6',
	},
	{
		id: 60,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '莓果奶酪鳳梨',
		ename: 'Cranberry & Pineapple-Filled Cream Cheese Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryPineappleFilledCreamCheeseMantou.webp',
		do: '天天有',
	},
	{
		id: 61,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '莓果奶酪雙果',
		ename: 'Passion fruit & Cranberry-Filled Cream Cheese Mantou',
		description: '百香果+蔓越莓',
		price: 38,
		type: '奶素 Lacto-Vegetarian',
		pic: './passionfruitCranberry-FilledCreamCheese.webp',
		do: '天天有',
		addedDate: '2025-12-25',
	},
	{
		id: 62,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '起司捲',
		ename: 'Cheese-Filled Mantou Roll',
		description: '提拉姆起司',
		price: 26,
		type: '奶素 Lacto-Vegetarian',
		pic: './cheeseFilledMantouRoll.webp',
		do: '天天有',
	},
	{
		id: 63,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '起司芋絲捲',
		ename: 'Taro-Shreds & Cheese-Filled Mantou Roll',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './taroShredsCheeseFilledMantouRoll.webp',
		do: '須預訂',
	},
	{
		id: 64,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '黃金起司芋絲捲',
		ename: 'Golden Taro-Shreds & Cheese-Filled Mantou Roll',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './goldenTaroShredsCheeseFilledMantouRoll.webp',
		do: '須預訂：2, 5',
	},
	{
		id: 65,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '黑糖鹹蛋奶酥',
		ename: 'Salted Egg & Creamy Milk Butter Brown Suger Mantou',
		description: '',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './saltedEggCreamyMilkButterBrownSugerMantou.webp',
		do: '天天有',
	},
	{
		id: 66,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '杏鮑菇起司',
		ename: 'King Oyster Mushroom-Filled Cheese Mantou',
		description: '',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './kingOysterMushroomFilledCheeseMantou.webp',
		do: '天天有',
	},
	{
		id: 67,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '藜麥杏鮑菇起司',
		ename: 'King Oyster Mushroom-Filled Quinoa Cheese Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './kingOysterMushroomFilledQuinoaCheeseMantou.webp',
		do: '須預訂：2, 5',
	},
	{
		id: 68,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '獅子頭',
		ename: 'Braised Meatball-Filled Mantou',
		description: '台畜',
		price: 43,
		type: '葷 Non Vegetarian',
		pic: './braisedMeatballFilledMantou.webp',
		do: '天天有',
	},
	{
		id: 69,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '梅干扣肉',
		ename: 'Pork with Salted Vegetables-Filled Mantou',
		description: '台畜',
		price: 46,
		type: '葷 Non Vegetarian',
		pic: './porkwithSaltedVegetablesFilledMantou.webp',
		do: '天天有',
	},
	{
		id: 70,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '燻雞起司',
		ename: 'Smoked Cheese Chicken-Filled Mantou',
		description: '正點',
		price: 36,
		type: '葷 Non Vegetarian',
		pic: './smokedCheeseChickenFilledMantou.webp',
		do: '天天有',
	},
	{
		id: 71,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '德式純肉香腸',
		ename: 'German Sausage Mantou',
		description: '台畜',
		price: 36,
		type: '葷 Non Vegetarian',
		pic: './germanSausageMantou.webp',
		do: '天天有',
	},
	{
		id: 72,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '辣子雞丁',
		ename: 'Chili Popcorn Chicken Mantou',
		description: '(基富) 小辣',
		price: 33,
		type: '葷 Non Vegetarian',
		pic: './chiliPopcornChickenMantou.webp',
		do: '天天有',
	},
	{
		id: 73,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '肉鬆核桃',
		ename: 'Meat Floss & Walnut-Filled Mantou',
		description: '',
		price: 28,
		type: '葷 Non Vegetarian',
		pic: './meatFlossWalnutFilledMantou.webp',
		do: '天天有',
	},
	{
		id: 74,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '肉鬆起司',
		ename: 'Meat Floss-Filled Cheese Mantou',
		description: '安佳起司',
		price: 28,
		type: '葷 Non Vegetarian',
		pic: './meatFlossFilledCheeseMantou.webp',
		do: '天天有',
	},
	{
		id: 75,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '肉鬆起司',
		ename: 'Meat Floss-Filled Cheese Mantou',
		description: '提拉姆起司',
		price: 33,
		type: '葷 Non Vegetarian',
		pic: './meatFlossFilledCheeseMantou.webp',
		do: '天天有',
	},
	{
		id: 76,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '燕麥南瓜鹹蛋',
		ename: 'Oatmeal & Salted Egg Pumpkin-Filled Mantou',
		description: '',
		price: 40,
		type: '奶素 Lacto-Vegetarian',
		pic: './wheatSaltedEggPumpkinFilledMantou.webp',
		do: '製作日：1, 6',
	},
	{
		id: 77,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '燕麥堅果起司',
		ename: 'Oatmeal & Nuts-Filled Cheese Mantou',
		description: '',
		price: 38,
		type: '奶素 Lacto-Vegetarian',
		pic: './wheatNutsFilledCheeseMantou.webp',
		do: '製作日：1, 6',
	},
	{
		id: 78,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '燕麥核桃素鬆',
		ename: 'Oatmeal & Vegetarian Floss-Filled Mantou',
		description: '非基改',
		price: 35,
		type: '素 Vegan',
		pic: './wheatVegetarianFlossFilledMantou.webp',
		do: '製作日：1, 6',
	},
	{
		id: 79,
		category: '(無糖)有內餡 No Sugar Added Fillings',
		name: '燕麥南瓜起司',
		ename: 'Oatmeal & Pumpkin-Filled Cheese Mantou',
		description: '',
		price: 38,
		type: '奶素 Lacto-Vegetarian',
		pic: './wheatPumpkinFilledCheeseMantou.webp',
		do: '製作日：1, 6',
	},
	{
		id: 80,
		category: '(無糖)有內餡 No Sugar Added Fillings',
		name: '燕麥南瓜多多',
		ename: 'Oatmeal & Pumpkin-Filled Mantou',
		description: '',
		price: 36,
		type: '素 Vegan',
		pic: './wheatPumpkinFilledMantou.webp',
		do: '製作日：1, 6',
	},
	{
		id: 81,
		category: '(無糖)有內餡 No Sugar Added Fillings',
		name: '乳酪南瓜',
		ename: 'Cheese & Pumpkin-Filled Milk Mantou',
		description: '牛奶/藜麥',
		price: 38,
		type: '奶素 Lacto-Vegetarian',
		pic: './cheesePumpkinFilled.webp',
		do: '天天有',
	},
	{
		id: 82,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋頭紅豆',
		ename: 'Taro & Red Bean-Filled Mantou',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './taroRedBeanFilledMantou.webp',
		do: '天天有',
	},
	{
		id: 83,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋泥鳳梨',
		ename: 'Mashed Taro & Pineapple-Filled Mantou',
		description: '',
		price: 36,
		type: '素 Vegan',
		pic: './mashedTaroPineappleFilled.webp',
		do: '天天有',
	},
	{
		id: 84,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋泥鳳梨',
		ename: 'Mashed Taro & Pineapple-Filled Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './mashedTaroPineappleFilled.webp',
		do: '天天有',
	},
	{
		id: 85,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶蔓越莓奶酥',
		ename: 'Cranberry & Creamy Milk Butter-Filled Matcha Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamyMilkButterFilledMatchaMantou.webp',
		do: '天天有',
	},
	{
		id: 86,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '玉米乳酪',
		ename: 'Corn & Cheese-Filled Mantou',
		description: '綠巨人非基改玉米粒,Saputo摩佐羅拉乾酪',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './cornCheeseFilled.webp',
		do: '天天有',
	},
];

// inventory = _.uniqBy(inventory, 'name')
const sortedInventory = _.sortBy(inventory, 'category');
const c = inventory.map((item) => item.category);
const t = inventory.map((item) => item.type);
const all = _.union(c, t);
// console.log('🚀 ~ all', all)

export const categories = _.uniq(all);
export default sortedInventory;

// console.log(inventory)
// console.log(categories)
