/*
 * @Date: 2023-01-02 04:31:36
 * @LastEditTime: 2023-01-23 01:35:11
 * @Description:
 */
/* eslint-disable indent */
/* eslint-disable no-tabs */
/* eslint-disable semi */
import _ from 'lodash';

// white-space: pre;

const inventory = [
	{
		id: 1,
		category: '(無糖)無內餡 No Sugar Added',
		name: '白饅頭\nPlain Mantou',
		description: '',
		price: 16,
		type: '素 Vegan',
		pic: './plainMantou.jpg',
		do: '',
	},
	{
		id: 2,
		category: '(無糖)無內餡 No Sugar Added',
		name: '伯爵牛奶饅頭\nEarl Milk Mantou',
		description: '唐寧',
		price: 27,
		type: '奶素 Lacto-Vegetarian',
		pic: './earlMilkMantou.jpg',
		do: '製作日：2, 6',
	},
	{
		id: 3,
		category: '(無糖)無內餡 No Sugar Added',
		name: '牛奶饅頭\nMilk Mantou',
		description: '紐西蘭奶粉',
		price: 22,
		type: '奶素 Lacto-Vegetarian',
		pic: './milkMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 4,
		category: '(無糖)無內餡 No Sugar Added',
		name: '藜麥饅頭\nQuinoa Mantou',
		description: '30%全麥',
		price: 22,
		type: '素 Vegan',
		pic: './quinoaMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 5,
		category: '(無糖)無內餡 No Sugar Added',
		name: '薑黃起司饅頭\nTurmeric Cheese Mantou',
		description: '提拉姆起司',
		price: 27,
		type: '奶素 Lacto-Vegetarian',
		pic: './turmericCheeseMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 6,
		category: '(無糖)無內餡 No Sugar Added',
		name: '全麥饅頭\nWhole-Wheat Mantou',
		description: '100%全麥',
		price: 20,
		type: '素 Vegan',
		pic: './wholeWheatMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 7,
		category: '(無糖)無內餡 No Sugar Added',
		name: '超麥饅頭\nNuts Whole-Wheat Mantou',
		description: '100%全麥, 核, 芝, 亞, 藜',
		price: 27,
		type: '素 Vegan',
		pic: './nutsWholeWheatMantou.jpg',
		do: '製作日：3',
	},
	{
		id: 8,
		category: '(無糖)無內餡 No Sugar Added',
		name: '穀物南瓜饅頭\nGrain Pumpkin Mantou',
		description: '50%全麥, 小米, 蕎麥, 藜麥',
		price: 27,
		type: '素 Vegan',
		pic: './grainPumpkinMantou.jpg',
		do: '製作日：6',
	},
	{
		id: 9,
		category: '(無糖)無內餡 No Sugar Added',
		name: '牛奶芋絲饅頭\nTaro Shreds Milk Mantou',
		description: '',
		price: 27,
		type: '奶素 Lacto-Vegetarian',
		pic: './taroShredsMilkMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 10,
		category: '(無糖)無內餡 No Sugar Added',
		name: '燕麥南瓜饅頭\nWheat Pumpkin Mantou',
		description: '50%全麥',
		price: 27,
		type: '素 Vegan',
		pic: './wheatPumpkinMantou.jpg',
		do: '製作日：1, 6',
	},
	{
		id: 11,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '黑糖饅頭\nBrown Suger Mantou',
		description: '',
		price: 17,
		type: '素 Vegan',
		pic: './brownSugerMantou.jpg',
		do: '',
	},
	{
		id: 12,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '芝麻多饅頭\nSesame Mantou',
		description: '',
		price: 23,
		type: '素 Vegan',
		pic: './sesameMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 13,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '紫米饅頭\nPurple Rice Mantou',
		description: '',
		price: 22,
		type: '素 Vegan',
		pic: './purpleRiceMantou.jpg',
		do: '須預訂',
	},
	{
		id: 14,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '可可饅頭\nCacao Mantou',
		description: '',
		price: 25,
		type: '素 Vegan',
		pic: './cacaoMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 15,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '抹茶饅頭\nMatcha Mantou',
		description: '自然農法抹茶',
		price: 25,
		type: '素 Vegan',
		pic: './matchaMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 16,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '土豆饅頭\nPeanut Mantou',
		description: '柴燒烘烤/金弘花生',
		price: 25,
		type: '素 Vegan',
		pic: './peanutMantou.jpg',
		do: '須預訂：5',
	},
	{
		id: 17,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '芋絲饅頭\nTaro-Shreds Mantou',
		description: '低糖微甜',
		price: 27,
		type: '素 Vegan',
		pic: './taroShredsMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 18,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '鐵觀音饅頭\nTieguanyin Mantou',
		description: '低糖微甜',
		price: 27,
		type: '素 Vegan',
		pic: './tieguanyinMantou.jpg',
		do: '製作日：1, 3',
	},
	{
		id: 19,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '莓果牛奶饅頭\nCranberry Milk Mantou',
		description: '低糖微甜',
		price: 27,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryMilkMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 20,
		category: '(有糖)無內餡 Low Sugar Added',
		name: '莓果饅頭\nBerries Mantou',
		description: '(低糖微甜) 黑, 藍, 覆盆, 蔓越莓',
		price: 27,
		type: '素 Vegan',
		pic: './berriesMantou.jpg',
		do: '',
	},
	{
		id: 21,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋頭多\nTaro-Filled Mantou',
		description: '',
		price: 35,
		type: '素 Vegan',
		pic: './taroFilledMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 22,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶芋頭多\nMilk Taro-Filled Mantou',
		description: '',
		price: 35,
		type: '奶素 Lacto-Vegetarian',
		pic: './taroFilledMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 23,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋頭紅豆\nTaro & Red Bean-Filled Mantou',
		description: '',
		price: 32,
		type: '奶素 Lacto-Vegetarian',
		pic: './taroRedBeanFilledMantou.jpg',
		do: '',
	},
	{
		id: 24,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋泥起司\nMashed Taro-Filled Cheese Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './01.jpg',
		do: '',
	},
	{
		id: 25,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芋泥肉鬆\nMashed Taro & Meat Floss-Filled Mantou',
		description: '',
		price: 36,
		type: '葷 Non Vegetarian',
		pic: './mashedTaroMeatFlossFilledMantou.jpg',
		do: '',
	},
	{
		id: 26,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '鐵觀音奶酪核桃\nWalnut & Cream Cheese-Filled Tieguanyin Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './walnutCreamCheeseFilledTieguanyinMantou.jpg',
		do: '製作日：1, 3',
	},
	{
		id: 27,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '鐵觀音紅豆\nRed Bean-Filled Tieguanyin Mantou',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './redBeanFilledTieguanyinMantou.jpg',
		do: '製作日：1, 3',
	},
	{
		id: 28,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '堅果多\nNuts-Filled Mantou',
		description: '',
		price: 33,
		type: '素 Vegan',
		pic: './nutsFilledMantou.jpg',
		do: '',
	},
	{
		id: 29,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '芝麻花生捲\nPeanut-Filled Sesame Mantou Roll',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './peanutFilledSesameMantouRoll.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 30,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '土豆芝麻捲\nSesame-Filled Peanut Mantou Roll',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './sesameFilledPeanutMantouRoll.jpg',
		do: '製作日：5',
	},
	{
		id: 31,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '土豆栗子\nChesnut-Filled Peanut Mantou',
		description: '',
		price: 35,
		type: '素 Vegan',
		pic: './chesnutFilledPeanutMantou.jpg',
		do: '製作日：5',
	},
	{
		id: 32,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可起司\nCacao Cheese Mantou',
		description: '',
		price: 32,
		type: '奶素 Lacto-Vegetarian',
		pic: './cacaoCheeseMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 33,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可栗子\nChesnut-Filled Cacao Mantou',
		description: '',
		price: 38,
		type: '素 Vegan',
		pic: './chesnutFilledCacaoMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 34,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可蔓越莓\nCranberry-Filled Cacao Mantou',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './cranberryFilledCacaoMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 35,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可奶酪蔓越莓\nCranberry & Cream Cheese-Filled Cacao Mantou',
		description: '菲力奶油',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamCheeseFilledCacaoMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 36,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶芝麻捲\nMilk & Sesame Mantou Roll',
		description: '',
		price: 32,
		type: '奶素 Lacto-Vegetarian',
		pic: './milkSesameMantouRoll.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 37,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶栗子起司\nChesnut & Cheese-Filled Milk Mantou',
		description: '',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './chesnutCheeseFilledMilkMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 38,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶奶酪蔓越莓\nCranberry & Cream Cheese-Filled Milk Mantou',
		description: '菲力奶油',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamCheeseFilledMilkMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 39,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '牛奶蔓越莓奶酥\nCranberry & Creamy Milk Butter-Filled Milk Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamyMilkButterFilledMilkMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 40,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '紫米堅果地瓜\nSweet Potato & Nuts-Filled Purple Rice Mantou',
		description: '',
		price: 35,
		type: '素 Vegan',
		pic: './sweetPotatoNutsFilledPurpleRiceMantou.jpg',
		do: '',
	},
	{
		id: 41,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '紫米紅豆\nRed Bean-Filled Purple Rice Mantou',
		description: '小紅豆+花豆',
		price: 28,
		type: '奶素 Lacto-Vegetarian',
		pic: './redBeanFilledPurpleRiceMantou.jpg',
		do: '',
	},
	{
		id: 42,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶奶酪栗子\nChesnut & Cream Cheese-Filled Matcha Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './chesnutCreamCheeseFilledMatchaMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 43,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶紅豆\nRed Bean-Filled Matcha Mantou',
		description: '小紅豆+花豆',
		price: 30,
		type: '素 Vegan',
		pic: './redBeanFilledMatchaMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 44,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶奶酪蔓越莓\nCranberry & Cream Cheese-Filled Matcha Mantou',
		description: '',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamCheeseFilledMatchaMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 45,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '抹茶芋頭\nTaro-Filled Matcha Mantou',
		description: '',
		price: 34,
		type: '素 Vegan',
		pic: './taroFilledMatchaMantou.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 46,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '藜麥芝麻捲\nQuinoa & Sesame Mantou Roll',
		description: '',
		price: 32,
		type: '素 Vegan',
		pic: './quinoaSesameMantouRoll.jpg',
		do: '製作日：2, 5',
	},
	{
		id: 47,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '藜麥芋頭\nTaro-Filled Quinoa Mantou',
		description: '',
		price: 34,
		type: '素 Vegan',
		pic: './taroFilledQuinoaMantou.jpg',
		do: '須預訂：2, 5',
	},
	{
		id: 48,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '藜麥堅果多\nNuts-Filled Quinoa Mantou',
		description: '無糖需預訂',
		price: 35,
		type: '素 Vegan',
		pic: './nutsFilledQuinoaMantou.jpg',
		do: '須預訂：2, 5',
	},
	{
		id: 49,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '起司紅豆\nRed Bean-Filled Cheese Mantou',
		description: '安佳起司',
		price: 28,
		type: '奶素 Lacto-Vegetarian',
		pic: './redBeanFilledCheeseMantou.jpg',
		do: '須預訂',
	},
	{
		id: 50,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '可可奶酥\nCreamy Milk Butter-Filled Cacao Mantou',
		description: '可可/抹茶/花生',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './creamyMilkButterFilledCacaoMantou.jpg',
		do: '製作日：1, 3, 6',
	},
	{
		id: 51,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '伯爵奶酥\nCreamy Milk Butter-Filled Earl Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './creamyMilkButterFilledEarlMantou.jpg',
		do: '製作日：2, 6',
	},
	{
		id: 52,
		category: '(甜)有內餡 Mantou with Sweet Fillings',
		name: '莓果奶酪鳳梨\nCranberry & Pineapple-Filled Cream Cheese Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryPineappleFilledCreamCheeseMantou.jpg',
		do: '',
	},
	{
		id: 53,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '起司捲\nCheese-Filled Mantou Roll',
		description: '提拉姆起司',
		price: 26,
		type: '奶素 Lacto-Vegetarian',
		pic: './cheeseFilledMantouRoll.jpg',
		do: '',
	},
	{
		id: 54,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '起司芋絲捲\nTaro-Shreds & Cheese-Filled Mantou Roll',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './taroShredsCheeseFilledMantouRoll.jpg',
		do: '須預訂',
	},
	{
		id: 55,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '黃金起司芋絲捲\nGolden Taro-Shreds & Cheese-Filled Mantou Roll',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './goldenTaroShredsCheeseFilledMantouRoll.jpg',
		do: '須預訂：2, 5',
	},
	{
		id: 56,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '黑糖鹹蛋奶酥\nSalted Egg & Creamy Milk Butter Brown Suger Mantou',
		description: '',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './saltedEggCreamyMilkButterBrownSugerMantou.jpg',
		do: '',
	},
	{
		id: 57,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '杏鮑菇起司\nKing Oyster Mushroom-Filled Cheese Mantou',
		description: '',
		price: 34,
		type: '奶素 Lacto-Vegetarian',
		pic: './kingOysterMushroomFilledCheeseMantou.jpg',
		do: '',
	},
	{
		id: 58,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '藜麥杏鮑菇起司\nKing Oyster Mushroom-Filled Quinoa Cheese Mantou',
		description: '',
		price: 36,
		type: '奶素 Lacto-Vegetarian',
		pic: './kingOysterMushroomFilledQuinoaCheeseMantou.jpg',
		do: '須預訂：2, 5',
	},
	{
		id: 59,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '獅子頭\nBraised Meatball-Filled Mantou',
		description: '台畜',
		price: 43,
		type: '葷 Non Vegetarian',
		pic: './braisedMeatballFilledMantou.jpg',
		do: '',
	},
	{
		id: 60,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '梅干扣肉\nPork with Salted Vegetables-Filled Mantou',
		description: '台畜',
		price: 46,
		type: '葷 Non Vegetarian',
		pic: './porkwithSaltedVegetablesFilledMantou.jpg',
		do: '',
	},
	{
		id: 61,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '燻雞起司\nSmoked Cheese Chicken-Filled Mantou',
		description: '正點',
		price: 36,
		type: '葷 Non Vegetarian',
		pic: './smokedCheeseChickenFilledMantou.jpg',
		do: '',
	},
	{
		id: 62,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '德式純肉香腸\nGerman Sausage Mantou',
		description: '台畜',
		price: 36,
		type: '葷 Non Vegetarian',
		pic: './germanSausageMantou.jpg',
		do: '',
	},
	{
		id: 63,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '辣子雞丁\nChili Popcorn Chicken Mantou',
		description: '(基富) 小辣',
		price: 33,
		type: '葷 Non Vegetarian',
		pic: './chiliPopcornChickenMantou.jpg',
		do: '',
	},
	{
		id: 64,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '肉鬆核桃\nMeat Floss & Walnut-Filled Mantou',
		description: '',
		price: 28,
		type: '葷 Non Vegetarian',
		pic: './meatFlossWalnutFilledMantou.jpg',
		do: '',
	},
	{
		id: 65,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '肉鬆起司\nMeat Floss-Filled Cheese Mantou',
		description: '安佳起司',
		price: 28,
		type: '葷 Non Vegetarian',
		pic: './meatFlossFilledCheeseMantou.jpg',
		do: '',
	},
	{
		id: 66,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '肉鬆起司\nMeat Floss-Filled Cheese Mantou',
		description: '提拉姆起司',
		price: 33,
		type: '葷 Non Vegetarian',
		pic: './meatFlossFilledCheeseMantou.jpg',
		do: '',
	},
	{
		id: 67,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '燕麥南瓜鹹蛋\nWheat & Salted Egg Pumpkin-Filled Mantou',
		description: '',
		price: 40,
		type: '奶素 Lacto-Vegetarian',
		pic: './wheatSaltedEggPumpkinFilledMantou.jpg',
		do: '製作日：1, 6',
	},
	{
		id: 68,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '燕麥堅果起司\nWheat & Nuts-Filled Cheese Mantou',
		description: '',
		price: 38,
		type: '奶素 Lacto-Vegetarian',
		pic: './wheatNutsFilledCheeseMantou.jpg',
		do: '製作日：1, 6',
	},
	{
		id: 69,
		category: '(鹹)有內餡 Mantou with Savory Fillings',
		name: '燕麥素鬆\nWheat & Vegetarian Floss-Filled Mantou',
		description: '',
		price: 35,
		type: '素 Vegan',
		pic: './wheatVegetarianFlossFilledMantou.jpg',
		do: '',
	},
	{
		id: 70,
		category: '(無糖)有內餡 No Sugar Added Fillings',
		name: '燕麥南瓜起司\nWheat & Pumpkin-Filled Cheese Mantou',
		description: '',
		price: 38,
		type: '奶素 Lacto-Vegetarian',
		pic: './wheatPumpkinFilledCheeseMantou.jpg',
		do: '製作日：1, 6',
	},
	{
		id: 71,
		category: '(無糖)有內餡 No Sugar Added Fillings',
		name: '燕麥南瓜多多\nWheat & Pumpkin-Filled Mantou',
		description: '',
		price: 36,
		type: '素 Vegan',
		pic: './wheatPumpkinFilledMantou.jpg',
		do: '製作日：1, 6',
	},
];

// inventory = _.uniqBy(inventory, 'name')
const sortedInventory = _.sortBy(inventory, 'category');
const c = inventory.map((item) => item.category);
const t = inventory.map((item) => item.type);
const all = _.union(c, t);
// console.log('🚀 ~ all', all)

export const categories = _.uniq(all);
export default sortedInventory;

// console.log(inventory)
// console.log(categories)
