/*
 * @Date: 2023-01-02 04:31:36
 * @LastEditTime: 2023-01-09 19:50:23
 * @Description:
 */
/* eslint-disable indent */
/* eslint-disable no-tabs */
/* eslint-disable semi */
import _ from 'lodash'

// white-space: pre;

const inventory = [
	{
		id: 1,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '白饅頭\n Plain Mantou',
		description: '',
		price: '16',
		type: '素 Vegan',
		pic: './plainMantou.jpg',
	},
	{
		id: 2,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '伯爵牛奶饅頭\n Earl Milk Mantou',
		description: '唐寧',
		price: '27',
		type: '奶素 Lacto-Vegetarian',
		pic: './earlMilkMantou.jpg',
	},
	{
		id: 3,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '牛奶饅頭\n Milk Mantou',
		description: '紐西蘭奶粉',
		price: '22',
		type: '奶素 Lacto-Vegetarian',
		pic: './milkMantou.jpg',
	},
	{
		id: 4,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '藜麥饅頭\n Quinoa Mantou',
		description: '30%全麥',
		price: '22',
		type: '素 Vegan',
		pic: './quinoaMantou.jpg',
	},
	{
		id: 5,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '薑黃起司饅頭\n Turmeric Cheese Mantou',
		description: '提拉姆起司',
		price: '27',
		type: '奶素 Lacto-Vegetarian',
		pic: './turmericCheeseMantou.jpg',
	},
	{
		id: 6,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '全麥饅頭\n Whole-Wheat Mantou',
		description: '100%全麥',
		price: '20',
		type: '素 Vegan',
		pic: './wholeWheatMantou.jpg',
	},
	{
		id: 7,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '超麥饅頭\n Nuts Whole-Wheat Mantou',
		description: '100%全麥, 核, 芝, 亞, 藜',
		price: '27',
		type: '素 Vegan',
		pic: './nutsWholeWheatMantou.jpg',
	},
	{
		id: 8,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '穀物南瓜饅頭\n Grain Pumpkin Mantou',
		description: '50%全麥, 小米, 蕎麥, 藜麥',
		price: '27',
		type: '素 Vegan',
		pic: './grainPumpkinMantou.jpg',
	},
	{
		id: 9,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '牛奶芋絲饅頭\n Taro Shreds Milk Mantou',
		description: '',
		price: '27',
		type: '奶素 Lacto-Vegetarian',
		pic: './taroShredsMilkMantou.jpg',
	},
	{
		id: 10,
		category: '(無糖)無內餡\n No Sugar Added',
		name: '燕麥南瓜饅頭\n Wheat Pumpkin Mantou',
		description: '50%全麥',
		price: '27',
		type: '素 Vegan',
		pic: './wheatPumpkinMantou.jpg',
	},
	{
		id: 11,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '黑糖饅頭\n Brown Suger Mantou',
		description: '',
		price: '17',
		type: '素 Vegan',
		pic: './brownSugerMantou.jpg',
	},
	{
		id: 12,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '芝麻多饅頭\n Sesame Mantou',
		description: '',
		price: '23',
		type: '素 Vegan',
		pic: './sesameMantou.jpg',
	},
	{
		id: 13,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '紫米饅頭\n Purple Rice Mantou',
		description: '',
		price: '22',
		type: '素 Vegan',
		pic: './purpleRiceMantou.jpg',
	},
	{
		id: 14,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '可可饅頭\n Cacao Mantou',
		description: '',
		price: '25',
		type: '素 Vegan',
		pic: './cacaoMantou.jpg',
	},
	{
		id: 15,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '抹茶饅頭\n Matcha Mantou',
		description: '自然農法抹茶',
		price: '25',
		type: '素 Vegan',
		pic: './matchaMantou.jpg',
	},
	{
		id: 16,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '土豆饅頭\n Peanut Mantou',
		description: '柴燒烘烤/金弘花生',
		price: '25',
		type: '素 Vegan',
		pic: './peanutMantou.jpg',
	},
	{
		id: 17,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '芋絲饅頭\n Taro-Shreds Mantou',
		description: '低糖微甜',
		price: '27',
		type: '素 Vegan',
		pic: './taroShredsMantou.jpg',
	},
	{
		id: 18,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '鐵觀音饅頭\n Tieguanyin Mantou',
		description: '低糖微甜',
		price: '27',
		type: '素 Vegan',
		pic: './tieguanyinMantou.jpg',
	},
	{
		id: 19,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '莓果牛奶饅頭\n Cranberry Milk Mantou',
		description: '低糖微甜',
		price: '27',
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryMilkMantou.jpg',
	},
	{
		id: 20,
		category: '(有糖)無內餡\n Low Sugar Added',
		name: '莓果饅頭\n Berries Mantou',
		description: '(低糖微甜) 黑, 藍, 覆盆, 蔓越莓',
		price: '27',
		type: '素 Vegan',
		pic: './berriesMantou.jpg',
	},
	{
		id: 21,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '芋頭多\n Taro-Filled Mantou',
		description: '',
		price: '35',
		type: '素 Vegan',
		pic: './taroFilledMantou.jpg',
	},
	{
		id: 22,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '牛奶芋頭多\n Milk Taro-Filled Mantou',
		description: '',
		price: '35',
		type: '奶素 Lacto-Vegetarian',
		pic: './milkTaroFilledMantou.jpg',
	},
	{
		id: 23,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '芋頭紅豆\n Taro & Red Bean-Filled Mantou',
		description: '',
		price: '32',
		type: '素 Vegan / 奶素 Lacto-Vegetarian',
		pic: './taroRedBeanFilledMantou.jpg',
	},
	{
		id: 24,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '芋泥起司\n Mashed Taro-Filled Cheese Mantou',
		description: '',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './mashedTaroFilledCheeseMantou.jpg',
	},
	{
		id: 25,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '芋泥肉鬆\n Mashed Taro & Meat Floss-Filled Mantou',
		description: '',
		price: '36',
		type: '葷 Non Vegetarian',
		pic: './mashedTaroMeatFlossFilledMantou.jpg',
	},
	{
		id: 26,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '鐵觀音奶酪核桃\n Walnut & Cream Cheese-Filled Tieguanyin Mantou',
		description: '',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './walnutCreamCheeseFilledTieguanyinMantou.jpg',
	},
	{
		id: 27,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '鐵觀音紅豆\n Red Bean-Filled Tieguanyin Mantou',
		description: '',
		price: '32',
		type: '素 Vegan',
		pic: './redBeanFilledTieguanyinMantou.jpg',
	},
	{
		id: 28,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '堅果多\n Nuts-Filled Mantou',
		description: '',
		price: '33',
		type: '素 Vegan',
		pic: './nutsFilledMantou.jpg',
	},
	{
		id: 29,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '芝麻花生捲\n Peanut-Filled Sesame Mantou Roll',
		description: '',
		price: '32',
		type: '素 Vegan',
		pic: './peanutFilledSesameMantouRoll.jpg',
	},
	{
		id: 30,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '土豆芝麻捲\n Sesame-Filled Peanut Mantou Roll',
		description: '',
		price: '32',
		type: '素 Vegan',
		pic: './sesameFilledPeanutMantouRoll.jpg',
	},
	{
		id: 31,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '土豆栗子\n Chesnut-Filled Peanut Mantou',
		description: '',
		price: '35',
		type: '素 Vegan',
		pic: './chesnutFilledPeanutMantou.jpg',
	},
	{
		id: 32,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '可可起司\n Cacao Cheese Mantou',
		description: '',
		price: '30',
		type: '奶素 Lacto-Vegetarian',
		pic: './cacaoCheeseMantou.jpg',
	},
	{
		id: 33,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '可可栗子\n Chesnut-Filled Cacao Mantou',
		description: '',
		price: '36',
		type: '素 Vegan',
		pic: './chesnutFilledCacaoMantou.jpg',
	},
	{
		id: 34,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '可可蔓越莓\n Cranberry-Filled Cacao Mantou',
		description: '',
		price: '30',
		type: '素 Vegan',
		pic: './cranberryFilledCacaoMantou.jpg',
	},
	{
		id: 35,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '可可奶酪蔓越莓\n Cranberry & Cream Cheese-Filled Cacao Mantou',
		description: '菲力奶油',
		price: '34',
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamCheeseFilledCacaoMantou.jpg',
	},
	{
		id: 36,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '牛奶芝麻捲\n Milk & Sesame Mantou Roll',
		description: '',
		price: '32',
		type: '奶素 Lacto-Vegetarian',
		pic: './milkSesameMantouRoll.jpg',
	},
	{
		id: 37,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '牛奶栗子起司\n Chesnut & Cheese-Filled Milk Mantou',
		description: '',
		price: '34',
		type: '奶素 Lacto-Vegetarian',
		pic: './chesnutCheeseFilledMilkMantou.jpg',
	},
	{
		id: 38,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '牛奶奶酪蔓越莓\n Cranberry & Cream Cheese-Filled Milk Mantou',
		description: '菲力奶油',
		price: '34',
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamCheeseFilledMilkMantou.jpg',
	},
	{
		id: 39,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '牛奶蔓越莓奶酥\n Cranberry & Creamy Milk Butter-Filled Milk Mantou',
		description: '',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamyMilkButterFilledMilkMantou.jpg',
	},
	{
		id: 40,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '紫米堅果地瓜\n Sweet Potato & Nuts-Filled Purple Rice Mantou',
		description: '',
		price: '35',
		type: '素 Vegan',
		pic: './sweetPotatoNutsFilledPurpleRiceMantou.jpg',
	},
	{
		id: 41,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '紫米紅豆\n Red Bean-Filled Purple Rice Mantou',
		description: '小紅豆+花豆',
		price: '28',
		type: '奶素 Lacto-Vegetarian',
		pic: './redBeanFilledPurpleRiceMantou.jpg',
	},
	{
		id: 42,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '抹茶奶酪栗子\n Chesnut & Cream Cheese-Filled Matcha Mantou',
		description: '',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './chesnutCreamCheeseFilledMatchaMantou.jpg',
	},
	{
		id: 43,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '抹茶紅豆\n Red Bean-Filled Matcha Mantou',
		description: '小紅豆+花豆',
		price: '30',
		type: '素 Vegan',
		pic: './redBeanFilledMatchaMantou.jpg',
	},
	{
		id: 44,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '抹茶奶酪蔓越莓\n Cranberry & Cream Cheese-Filled Matcha Mantou',
		description: '',
		price: '34',
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryCreamCheeseFilledMatchaMantou.jpg',
	},
	{
		id: 45,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '抹茶芋頭\n Taro-Filled Matcha Mantou',
		description: '',
		price: '34',
		type: '素 Vegan',
		pic: './taroFilledMatchaMantou.jpg',
	},
	{
		id: 46,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '藜麥芝麻捲\n Quinoa & Sesame Mantou Roll',
		description: '',
		price: '32',
		type: '素 Vegan',
		pic: './quinoaSesameMantouRoll.jpg',
	},
	{
		id: 47,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '藜麥芋頭\n Taro-Filled Quinoa Mantou',
		description: '',
		price: '34',
		type: '素 Vegan',
		pic: './taroFilledQuinoaMantou.jpg',
	},
	{
		id: 48,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '藜麥堅果多\n Nuts-Filled Quinoa Mantou',
		description: '無糖需預訂',
		price: '35',
		type: '素 Vegan',
		pic: './nutsFilledQuinoaMantou.jpg',
	},
	{
		id: 49,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '起司紅豆\n Red Bean-Filled Cheese Mantou',
		description: '安佳起司',
		price: '28',
		type: '奶素 Lacto-Vegetarian',
		pic: './redBeanFilledCheeseMantou.jpg',
	},
	{
		id: 50,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '可可奶酥\n Creamy Milk Butter-Filled Cacao Mantou',
		description: '可可/抹茶/花生',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './creamyMilkButterFilledCacaoMantou.jpg',
	},
	{
		id: 51,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '伯爵奶酥\n Creamy Milk Butter-Filled Earl Mantou',
		description: '',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './creamyMilkButterFilledEarlMantou.jpg',
	},
	{
		id: 52,
		category: '(甜)有內餡\n Mantou with Sweet Fillings',
		name: '莓果奶酪鳳梨\n Cranberry & Pineapple-Filled Cream Cheese Mantou',
		description: '',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './cranberryPineappleFilledCreamCheeseMantou.jpg',
	},
	{
		id: 53,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '起司捲\n Cheese-Filled Mantou Roll',
		description: '提拉姆起司',
		price: '26',
		type: '奶素 Lacto-Vegetarian',
		pic: './cheeseFilledMantouRoll.jpg',
	},
	{
		id: 54,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '起司芋絲捲\n Taro-Shreds & Cheese-Filled Mantou Roll',
		description: '',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './taroShredsCheeseFilledMantouRoll.jpg',
	},
	{
		id: 55,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '黃金起司芋絲捲\n Golden Taro-Shreds & Cheese-Filled Mantou Roll',
		description: '',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './goldenTaroShredsCheeseFilledMantouRoll.jpg',
	},
	{
		id: 56,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '黑糖鹹蛋奶酥\n Salted Egg & Creamy Milk Butter Brown Suger Mantou',
		description: '',
		price: '34',
		type: '奶素 Lacto-Vegetarian',
		pic: './saltedEggCreamyMilkButterBrownSugerMantou.jpg',
	},
	{
		id: 57,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '杏鮑菇起司\n King Oyster Mushroom-Filled Cheese Mantou',
		description: '',
		price: '34',
		type: '奶素 Lacto-Vegetarian',
		pic: './kingOysterMushroomFilledCheeseMantou.jpg',
	},
	{
		id: 58,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '藜麥杏鮑菇起司\n King Oyster Mushroom-Filled Quinoa Cheese Mantou',
		description: '',
		price: '36',
		type: '奶素 Lacto-Vegetarian',
		pic: './kingOysterMushroomFilledQuinoaCheeseMantou.jpg',
	},
	{
		id: 59,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '獅子頭\n Braised Meatball-Filled Mantou',
		description: '台畜',
		price: '43',
		type: '葷 Non Vegetarian',
		pic: './braisedMeatballFilledMantou.jpg',
	},
	{
		id: 60,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '梅干扣肉\n Pork with Salted Vegetables-Filled Mantou',
		description: '台畜',
		price: '46',
		type: '葷 Non Vegetarian',
		pic: './porkwithSaltedVegetablesFilledMantou.jpg',
	},
	{
		id: 61,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '燻雞起司\n Smoked Cheese Chicken-Filled Mantou',
		description: '正點',
		price: '36',
		type: '葷 Non Vegetarian',
		pic: './smokedCheeseChickenFilledMantou.jpg',
	},
	{
		id: 62,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '德式純肉香腸\n German Sausage Mantou',
		description: '台畜',
		price: '36',
		type: '葷 Non Vegetarian',
		pic: './germanSausageMantou.jpg',
	},
	{
		id: 63,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '辣子雞丁\n Chili Popcorn Chicken Mantou',
		description: '(基富) 小辣',
		price: '33',
		type: '葷 Non Vegetarian',
		pic: './chiliPopcornChickenMantou.jpg',
	},
	{
		id: 64,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '肉鬆核桃\n Meat Floss & Walnut-Filled Mantou',
		description: '',
		price: '28',
		type: '葷 Non Vegetarian',
		pic: './meatFlossWalnutFilledMantou.jpg',
	},
	{
		id: 65,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '肉鬆起司\n Meat Floss-Filled Cheese Mantou',
		description: '安佳起司',
		price: '28',
		type: '葷 Non Vegetarian',
		pic: './meatFlossFilledCheeseMantou.jpg',
	},
	{
		id: 66,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '肉鬆起司\n Meat Floss-Filled Cheese Mantou',
		description: '提拉姆起司',
		price: '33',
		type: '葷 Non Vegetarian',
		pic: './meatFlossFilledCheeseMantou.jpg',
	},
	{
		id: 67,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '燕麥南瓜鹹蛋\n Wheat & Salted Egg Pumpkin-Filled Mantou',
		description: '',
		price: '40',
		type: '奶素 Lacto-Vegetarian',
		pic: './wheatSaltedEggPumpkinFilledMantou.jpg',
	},
	{
		id: 68,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '燕麥堅果起司\n Wheat & Nuts-Filled Cheese Mantou',
		description: '',
		price: '35',
		type: '奶素 Lacto-Vegetarian',
		pic: './wheatNutsFilledCheeseMantou.jpg',
	},
	{
		id: 69,
		category: '(鹹)有內餡\n Mantou with Savory Fillings',
		name: '燕麥素鬆\n Wheat & Vegetarian Floss-Filled Mantou',
		description: '',
		price: '35',
		type: '素 Vegan',
		pic: './wheatVegetarianFlossFilledMantou.jpg',
	},
	{
		id: 70,
		category: '(無糖)有內餡\n No Sugar Added Fillings',
		name: '燕麥南瓜起司\n Wheat & Pumpkin-Filled Cheese Mantou',
		description: '',
		price: '38',
		type: '奶素 Lacto-Vegetarian',
		pic: './wheatPumpkinFilledCheeseMantou.jpg',
	},
	{
		id: 71,
		category: '(無糖)有內餡\n No Sugar Added Fillings',
		name: '燕麥南瓜多多\n Wheat & Pumpkin-Filled Mantou',
		description: '',
		price: '36',
		type: '素 Vegan',
		pic: './wheatPumpkinFilledMantou.jpg',
	},
]

// inventory = _.uniqBy(inventory, 'name')
const sortedInventory = _.sortBy(inventory, 'category')
const c = inventory.map(item => item.category)
const t = inventory.map(item => item.type)
const all = _.union(c, t)
// console.log('🚀 ~ all', all)

export const categories = _.uniq(all)
export default sortedInventory

// console.log(inventory)
// console.log(categories)
